apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/cluster-registration-controller/base
- components/gitops-service/base
- components/spi-controller/base
- components/spi-oauth-service/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
