apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-oauth-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-oauth-service
    app.kubernetes.io/part-of: try-out-appstudio-build
  name: spi-oauth-service
  namespace: shbose
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: spi-oauth-service
status:
  loadBalancer: {}
